USE fasichatroom;

-- Roles
INSERT INTO roles (name, description) VALUES
('etudiant', 'Étudiant'),
('enseignant', 'Enseignant'),
('assistant', 'Assistant'),
('doyen', 'Doyen'),
('vicedoyen', 'Vice-Doyen'),
('apparitaire', 'Apparitaire');

-- Promotions
INSERT INTO promotions (name, level, year) VALUES
('L2 FASI', 'Licence 2', 2024),
('L3 FASI', 'Licence 3', 2024);

-- Example courses (you can assign teachers later)
INSERT INTO cours (code, titre, description, teacher_id, promotion_id) VALUES
('PHP-POO-L2', 'PHP POO — L2', 'Programmation orientée objet en PHP', NULL, 1),
('WEB-L2', 'Programmation Web — L2', 'Introduction au développement Web', NULL, 1);

-- Note: create user accounts via the application or insert manually with hashed passwords.

INSERT INTO utilisateurs (matricule, nom, email, motDePasse, role, dateCreation, promotion_id) VALUES
('SI2024001', 'Étudiant Exemple', 'etu1@example.com', '$2y$10$Pt.oACyeelQ14pWTivQ/feGwyDa6qC/48OtRhRZTGrLgV2b4fV4Ai', 'etudiant', NOW(), 1),
('ENS2024001', 'Enseignant Exemple', 'ens1@example.com', '$2y$10$wwSwauumQYpVhTv56SY6MugWsdLGo0ERbHau.OJQgPcm4nsUBU.d2', 'enseignant', NOW(), NULL),
('ASS2024001', 'Assistant Exemple', 'ass1@example.com', '$2y$10$bVFl1XVefiLj4Bt.6BpOB.omOgPG7WBmklySUBHjXC3C1/VR/76sm', 'assistant', NOW(), NULL);

-- Test users removed. Create users via application or use a separate secure script to insert users with
-- password hashes generated by PHP's password_hash().
